version: '3.8'

services:
  http_api:
    container_name: http_api
    depends_on:
      - postgres_db

  selenium:
    container_name: selenium

  minio:
    container_name: minio

  postgres_db:
    image: postgres:latest
    container_name: pgdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - "./dump/:/docker-entrypoint-initdb.d/"
      - screenshot_db_data:/var/lib/postgresql/data