version: '3.8'

services:
  http_api:
    container_name: http_api
    depends_on:
      - postgres_db
      - selenium
    command:
      uvicorn http_api.main:app --reload

  selenium:
    container_name: selenium_work
    depends_on:
      - minio
      - postgres_db
    build:
      dockerfile: src/selenium_work/Dockerfile

  minio:
    container_name: minio_work
    ports:
      - "9000:9000"
    environment:
      - MINIO_HTTP=${MINIO_HTTP}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
    build:
      dockerfile: src/minio_work/Dockerfile
    volumes:
      - minio_data:/bitnami/minio_work/data


  postgres_db:
    image: postgres:latest
    container_name: pgdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - "./dump/:/docker-entrypoint-initdb.d/"
      - screenshot_db_data:/var/lib/postgresql/data
volumes:
  screenshot_db_data:

  minio_data: